#!/usr/bin/env bash

REPO_DIR=$(dirname $(dirname $(realpath $0)))

CONFIG=$HOME/.config
ZSH_CONFIG=$CONFIG/zshrc
NVIM_CONFIG=$CONFIG/nvim
HYPR_CONFIG=$CONFIG/hypr
WAYBAR_CONFIG=$CONFIG/waybar
WAYPAPER_CONFIG=$CONFIG/waypaper
KITTY_CONFIG=$CONFIG/kitty
ZATHURA_CONFIG=$CONFIG/zathura
FASTFETCH_CONFIG=$CONFIG/fastfetch
