font_family      Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Cursor
cursor #cccccc
cursor_text_color background
cursor_beam_thickness 1.5

# Theme
include ./themes/OneDark.conf

# Scrollback
scrollback_lines 2000


# Bell
enable_audio_bell no


# Window layout
window_border_width 0pt
