font_family      Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Cursor
cursor #cccccc
cursor_text_color background
cursor_beam_thickness 1.5

include ./themes/OneDark.conf

scrollback_lines 2000
enable_audio_bell no
