version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
  rust = '#d3462a'

[transient_prompt]
  template = '  '
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ .Path }}'
    foreground = 'p:pink'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = ''
      home_icon = '~'
      style = 'agnoster_full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Venv }}'
    foreground = 'p:blue'
    type = 'python'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ .Full }}'
    foreground = 'p:blue'
    type = 'go'

  [[blocks.segments]]
    style = 'plain'
    template = ' 󱘗 {{ .Full }}'
    foreground = 'p:rust'
    type = 'rust'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 500

  [[blocks.segments]]
    style = 'plain'
    foreground = 'p:pink'
    type = 'time'

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }} '
    foreground = 'p:lavender'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = ' '
    foreground = 'p:closer'
    type = 'text'
