- name:  Linking config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "zshrc", dest: "{{ ansible_env.HOME }}/.config/zshrc" }
    - { src: ".zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
    - { src: ".warprc", dest: "{{ ansible_env.HOME }}/.config/.warprc" }
