- name:  Linking config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "hypr", dest: "{{ ansible_env.HOME }}/.config/hypr" }
    - { src: "waypaper", dest: "{{ ansible_env.HOME }}/.config/waypaper" }
    - { src: "waybar", dest: "{{ ansible_env.HOME }}/.config/waybar" }
    - { src: "tofi", dest: "{{ ansible_env.HOME }}/.config/tofi" }
