- name:  Linking config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "kitty", dest: "{{ ansible_env.HOME }}/.config/kitty" }
    - { src: "zathura", dest: "{{ ansible_env.HOME }}/.config/zathura" }
