- name:  Linking config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "nvim", dest: "{{ ansible_env.HOME }}/.config/nvim" }
