[colors]
foreground = #ffffffff
background = #000000
grey = #414868
# disabled
border = #414868 

[bar/bottom]
width = 100%
height = 29
radius = 11
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 0pt
border-size = 0px
border-color = ${colors.border}
padding-left = 1
padding-right = 1
module-margin = 0
bottom = true
separator = "|"
separator-foreground = ${colors.grey}
separator-background = ${colors.background}
font-0 = "Hack Nerd Font:pixelsize=13;2"
# modules-left = reload-bar exit i3
modules-left = reload-bar i3
# modules-center =  memory filesystem temperature fan arch-update timezones
# modules-center =  memory temperature fan arch-update
modules-right =    filesystem memory temperature fan arch-update wlan eth battery date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
wm-restack = i3
tray-background = ${colors.background}
tray-position = none
tray-maxsize = 16

[module/margin]
type = custom/text
content = %{T1} %{T-}
content-foreground = ${colors.trans}

[module/battery]
type = internal/battery
low-at = 15
full-at = 99
battery = BAT0
adapter = ACAD
poll-interval = 5
time-format = %H%M
format-charging = <animation-charging> <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
format-low = <label-low> <animation-low>
label-charging = %percentage%%
label-discharging = %percentage%󱉸
format-discharging-background = ${colors.background}
label-full = %percentage%%
label-low = %percentage%%
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-low-0 = !
animation-low-1 =
animation-low-framerate = 200
animation-charging-0-foreground = ${colors.shade-1}
animation-charging-1-foreground = ${colors.shade-2}
animation-charging-2-foreground = ${colors.shade-3}
animation-charging-3-foreground = ${colors.shade-4}
animation-charging-4-foreground = ${colors.shade-5}
content-background = ${colors.background}

[module/date]
type = internal/date
interval = 8
date-alt =%H:%M:%S
date=%a %d %b %H:%M:%S
label = %date%
label-foreground = ${colors.white}
format-background = ${colors.background}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/i3]
type = internal/i3
pin-workspaces = false
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true
format =  <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 0
label-mode-background = ${colors.background}
label-mode-foreground = ${colors.white}
label-focused = %icon%%name%
label-focused-foreground = ${colors.white}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.background}
label-focused-padding = 1
label-unfocused = %icon%%name%
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.grey}
label-unfocused-background = ${colors.background}
label-visible = %icon%
label-visible-underline = #555555
label-visible-padding = 1
label-urgent = %index%
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background}
label-urgent-padding = 1
label-separator =
label-separator-padding = 0
label-separator-foreground = ${colors.foreground}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
label-connected-background = ${colors.background}

[module/wlan]
inherit = network-base
interface-type = wireless
# label-connected =󰖩
label-connected = %ifname% %local_ip%
label-connected-background = ${colors.background}
label-connected-foreground = ${colors.white}
label-connected-padding = 0
# label-disconnected ="󰖪 "
label-disconnected = %ifname% %local_ip%
label-disconnected-background =${colors.background}
label-disconnected-foreground =${colors.grey}
content-foreground = ${colors.primary}

[module/eth]
inherit = network-base
interface-type = wired
;
; Default: %ifname% %local_ip%
label-connected = %ifname% %local_ip%
# label-connected =󰈁
label-connected-background = ${colors.background}
label-connected-foreground = ${colors.white}
label-disconnected-background = ${colors.background}
label-disconnected-foreground = ${colors.grey}
label-disconnected =󰈂

[module/arch-update]
type = custom/script
exec = ~/bin/arch-update
tail = true
label =  󰮯 %output%
interval = 7200

[module/timer]
type = custom/script
exec = ~/bin/timer 1:00:00
tail = true
label =  %output%
interval = 5

[module/exit]
type = custom/script
exec = echo ' 󰈆 '
label = %output%
click-left = i3-msg exit

[module/uptime]
type = custom/script
exec = /usr/bin/uptime -p
tail = true

[module/info-hackspeed]
type = custom/script
exec = ~/.config/polybar/scripts/info-hackspeed.sh
tail = true

[module/info-kernel]
type = custom/script
exec = uname -r
interval = 1024

[module/timezones]
type = custom/script
exec = ~/bin/timezones.sh
label = %output%
tail = true

[module/memory]
type = internal/memory
interval = 5
exec = i3-msg workspace 8
warn-percentage = 95
label = 󰍛 %percentage_used%%
label-warn = %percentage_used%%
bar-used-indicator =
bar-used-width = 10

[module/filesystem]
type = internal/fs
mount-0 = /
mount-1 = /mnt/usb
interval = 30
fixed-values = true
spacing = 1
warn-percentage = 75
format-mounted = <label-mounted>
format-unmounted = <label-unmounted>
label-mounted =%mountpoint%: %free%
# label-unmounted = %mountpoint%: not mounted
label-unmounted =""
label-unmounted-foreground = #55

[fs-base]
type = internal/fs
fixed-values = true
label-mounted = %mountpoint%: %free%

[module/fs-root]
inherit = fs-base
mount-0 = /
label-mounted = / %free%

[module/fs-usb]
inherit = fs-base
mount-0 = /mnt/usb
label-mounted = usb: %free%%
label-unmounted = usb: not mounted

[module/subscriber]
type = custom/ipc
hook-0 = pwd
hook-1 = whoami
hook-2 = echo "Files in ${HOME}: $(ls -1a ~ | wc -l)"
initial = 1

[module/title]
type = internal/xwindow
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 4
label = %title%
label-maxlen = 50
label-empty = Empty
label-empty-foreground = #707880

[module/temperature]
type = internal/temperature
interval = 5
thermal-zone = 0
zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
base-temperature = 0
warn-temperature = 75
units = true
format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = #f00
ramp-0 = A
ramp-1 = B
ramp-2 = C
ramp-foreground = #55

[module/reload-bar]
type = custom/script
exec = echo ' '
label = %output%
click-left = polybar-msg cmd restart

[module/fan]
type = custom/script
exec = sensors | grep fan | cut -d : -f 2 | sed 's/ //g'
interval = 15
label = %output%

# TODO: this

# [module/connect-to-smartphone]
# type = custom/script
# exec = echo 'hotspot'
# # label = %output%
# click-left = hotspot c

