# Installing packages ------------------------------
- name: Installing dev packages
  kewlfft.aur.aur:
    name: "{{ app }}"
    use: yay
    state: latest
  loop: "{{ arch_apps }}"
  loop_control:
    loop_var: app
  when: ansible_os_family == 'Archlinux'


# Symlinking ------------------------------
- name:  Symlinking config files of dev tools
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "nvim", dest: "{{ ansible_env.HOME }}/.config/nvim" }
  tags: 
    - symlink
