arch_apps:
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - git
  - oh-my-posh
  - fastfetch
  - yazi
  - python

darwin_apps:
  - zsh
  - git
  - oh-my-posh
  - fastfetch
  - yazi
  - python
