- name:  Linking config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "zshrc", dest: "{{ ansible_env.HOME }}/.config/zshrc" }
    - { src: ".zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
    - { src: ".warprc", dest: "{{ ansible_env.HOME }}/.warprc" }
    - { src: "DOTFILES_ENV_VARS", dest: "{{ ansible_env.HOME }}/.config/DOTFILES_ENV_VARS" }
    - { src: "ohmyposh", dest: "{{ ansible_env.HOME }}/.config/ohmyposh" }
    - { src: "fastfetch", dest: "{{ ansible_env.HOME }}/.config/fastfetch" }
    - { src: "yazi", dest: "{{ ansible_env.HOME }}/.config/yazi" }
    - { src: ".tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
    - { src: "scripts" , dest: "{{ ansible_env.HOME }}/.local/bin" }
    - { src: "lazygit", dest: "{{ ansible_env.HOME }}/.config/lazygit" }
